# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Electronic Digerator Science 2000+
tagline:          "Le oueblogue de #devroom@ulminfo.fr"
# url:              http://getpoole.com
paginate:         1
baseurl:          /
# author:
#   name:           Mark Otto
#   url:            https://twitter.com/mdo
#   email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/electronicdigeratorscience2000plus/electronicdigeratorscience2000plus.github.io

# Markdown parser
markdown:  kramdown

