# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Électronique Digérateur Science 2000+
tagline:             "Le oueblogue de #devroom@ulminfo.fr"
description:         <abbr title="Électronique Digérateur Science 2000+">ÉDS2k+</abbr> est un blog collaboratif maintenu par des étudiants. Il a vocation à parler de maths, d'informatique et de plein d'autres choses scientifiques…
url:                 http://digerateur.xyz
baseurl:             /
paginate:            5

# About/contact
author:
  name:              JP Duzboub
  url:               http://digerateur.xyz
  email:             foo@bar.baz

# Custom vars
version:             1.0.0

